apiVersion: v1
kind: Service
metadata:
  name: ai-voice-service
spec:
  type: NodePort  # Change to LoadBalancer if using Cloud
  selector:
    app: ai-voice-assistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30008  # Optional (Minikube)
